author_Names = {
1: ['Lovecraft','Supernatural Horror in Fiction'],
2: ['Lois Tyson','Lois','Tyson','Psychoanalytic Criticism','Critical Theory Today','Critical Theory Today: A User-Friendly Guide'],
3: ['Michael Moorcock','Moorcock','Foreword'],
4: ['Jeff','VanderMeer','Ann','VanderMeer','Introduction'],
5: ['Sigmund Freud','Sigmund','Freud','The Uncanny'],
6: ['Alfred Kubin','Alfred','Kubin','The Other Side'],
7: ['F. Marion Crawford','Marion Crawford','The Screaming Skull'],
8: ['Algernon Blackwood','Algernon','Blackwood','The Willows'],
9: ['Saki','Sredni Vashtar'],
10: ['M. R. James','M. R.','Casting the Runes'],
11: ['Lord Dunsany','How Nuth Would Have Practised His Art Upon the Gnoles'],
12: ['Gustav Meyrink','Gustav','Meyrink','The Man in the Bottle'],
13: ['Georg Heym','Heym','The Dissection'],
14: ['Hans Heinz Ewers','Hans','Heinz','Ewers','The Spider'],
15: ['Rabindranath Tagore','Rabindranath','Tagore','The Hungry Stones'],
16: ['Luigi Ugolini','Luigi','Ugolini','The Vegetable Man'],
17: ['A. Merritt','Merritt','The People of the Pit'],
18: ['Ryonuoskue Akutagawa','Ryonuoskue','Akutagawa','The Hell Screen'],
19: ['Francis Stevens','Francis','Unseen-Unfeared'],
20: ['In the Penal Colony'],
21: ['Stefan Grabinski','Stefan','Grabinski','The White Wyrak'],
22: ['H. F. Arnold','H. F.','Arnold','The Night Wire'],
23: ['The Dunwich Horror', 'Dunwich Horror'],
24: ['Margaret Irwin','Irwin','The Book'],
25: ['Mainz','Psalter,' 'The Mainz Psalter'],
26: ['Shadowy','The Shadowy Street'],
27: ['Charles Lamb', 'Lamb'],
28: ['Clark Ashton Smith','Clark','Ashton Smith','Genius Loci'],
29: ['Hagiwara Sakutaro','Hagiwara','Sakutaro','The Town of Cats'],
30: ['Hugh Walpole','Hugh','Walpole','The Tarn'],
31: ['Bruno Schulz','Bruno','Schulz','Sanatorium under the Sign of the ourglass'],
32: ['Robert Barbour Johnson','Barbour Johnson','Far Below'],
33: ['Fritz Lieber','Fritz','Lieber','Smoke Ghost'],
34: ['Leonora Carrington','Leonora','Carrington','White Rabbits'],
35: ['Donald A. Wollheim','Donald','A. Wollheim','Mimic'],
36: ['Ray Bradbury','Ray','Bradbury','The Crowd'],
37: ['The Long Sheet'],
38: ['Jorge Luis Borges','Jorge','Luis Borges','The Aleph'],
39: ['Olympe Bhely-Quenum','Olympe','Bhely-Quenum','A Child in the Bush of hosts'],
40: ['Summer People','The Summer People'],
41: ['Margaret St. Clair','St. Clair','The Man Who Sold Rope to he Gnoles'],
42: ['Robert Bloch','Bloch','The Hungry House'],
43: ['Amos Tutuola','Amos','Tutuola','The Complete Gentleman'],
44: ['Jerome Bixby','Jerome','Bixby',"It's a Good Life"],
45: ['Augusto Monterroso','Augusto','Monterroso','Mister Taylor'],
46: ['Julio Cortazar','Julio','Cortazar','Axolotl'],
47: ['A Woman Seldom','A Woman Seldom Found'],
48: ['Charles Beaumont','Beaumont','The Howling Man'],
49: ['Mervyn Peake','Mervyn','Peake','Same Time',' Same Place'],
50: ['Colomber','The Colomber'],
51: ['Michel Bernanos','Michel','Bernanos','The Other Side of the Mountain'],
52: ['Merce Rodoreda','Merce','Rodoreda','The Salamander'],
53: ['Claude Seignolle','Claude','Seignolle','The Ghoulbird'],
54: ['Gahan Wilson','Gahan','Wilson','The Sea Was Wet As Wet Could Be'],
55: ['Daphne du Maurier','Daphne','du Maurier',"Don't Look Now"],
56: ['Robert Aickman','Aickman','The Hospice'],
57: ['Dennis Etchison','Dennis','Etchison','It Only Comes Out at Night'],
58: ['James Tiptree','Tiptree',"The Psychologist Who Wouldn't Do errible Things to Rats"],
59: ['Eric Basso','Basso','The Beak Doctor'],
60: ['Jamaica Kincaid','Jamaica','Kincaid','My Mother'],
61: ['George R. R. Martin','R. R. Martin','Sandkings'],
62: ['Bob Leman','Bob','Leman','Window'],
63: ['Ramsey Campbell','Ramsey','Campbell','The Brood'],
64: ['Michael Shea','Shea','The Autopsy'],
65: ['William Gibson/John Shirley','Gibson/John Shirley','The elonging Kind'],
66: ['Egnaro'],
67: ['Joanna Russ','Joanna','Russ','The Little Dirty Girl'],
68: ['The New Rays'],
69: ['Premendra Mitra','Premendra','Mitra','The Discovery of Telenapota'],
70: ['F. Paul Wilson','Paul Wilson','Soft'],
71: ['Octavia E. Butler','Octavia','E. Butler','Bloodchild'],
72: ['Clive Barker','Clive','Barker','In the Hills, the Cities','the Cities'],
73: ['Leena Krohn','Leena','Krohn','Tainaron: Mail From Another City'],
74: ['Garry Kilworth','Garry','Kilworth','Hogfoot Right and Bird-hands'],
75: ['Lucius Shepard','Lucius','Shepard','Shades'],
76: ['Harlan Ellison','Harlan','Ellison','The Function of Dream Sleep'],
77: ['Ben Okri','Okri','Worlds That Flourish'],
78: ['Elizabeth Hand','Elizabeth','Hand','The Boy in the Tree'],
79: ['Joyce Carol Oates','Joyce','Carol Oates','Family'],
80: ['Poppy Z. Brite','Poppy','Z. Brite','His Mouth Will Taste of Wormwood'],
81: ['Michal Ajvaz','Michal','Ajvaz','The End of the Garden'],
82: ['Karen Joy Fowler','Joy Fowler','The Dark'],
83: ['Kathe Koja','Kathe','Koja','Angels in Love'],
84: ['Haruki Murakami','Haruki','Murakami','The Ice Man'],
85: ['Lisa Tuttle','Lisa','Tuttle','Replacements'],
86: ['Marc Laidlaw','Laidlaw','The Diane Arbus Suicide Portfolio'],
87: ['Steven Utley','Utley','The Country Doctor'],
88: ['Martin Simpson','Simpson','Last Rites and Resurrections'],
89: ['William Browning Spencer','Browning Spencer','The Ocean and ll Its Devices'],
90: ['Delicate','The Delicate'],
91: ['Stephen King','King','The Man in the Black Suit'],
92: ['Angela Carter','Angela','Carter','The Snow Pavilion'],
93: ['Craig Padawer','Craig','Padawer','The Meat Garden'],
94: ['Stepan Chapman','Stepan','Chapman','The Stiff and the Stile'],
95: ['Tanith Lee','Tanith','Lee','Yellow and Red'],
96: ['Kelly Link','Link',"The Specialist's Hat"],
97: ['Caitlin R. Kiernan','Caitlin','R. Kiernan','A Redress for Andromeda'],
98: ['Michael Chabon','Michael','Chabon','The God of Dark Laughter'],
99: ['Details'],
100: ['Michael Cisco','Cisco','The Genius of Assassins'],
101: ['Neil Gaiman','Neil','Gaiman','Feeders and Eaters'],
102: ['Jeff VanderMeer','VanderMeer','The Cage'],
103: ['The Beautiful Gelreesh', 'Beautiful Gelreesh'],
104: ['Thomas Ligotti','Ligotti','The Town Manager'],
105: ['Brian Evenson','Evenson','The Brotherhood of Mutilation'],
106: ['Mark Samuels','Samuels','The White Hands'],
107: ['Daniel Abraham','Abraham','Flat Diane'],
108: ['Margo Lanagan','Margo','Lanagan','Singing My Sister Down'],
109: ['T. M. Wright','T.','M. Wright','The People on the Island'],
110: ['Laird Barron','Laird','Barron','The Forest'],
111: ['Liz Williams','The Hide'],
112: ['Reza Negarestani','Reza','Negarestani','Dust Enforcer'],
113: ['Micaela Morrissette','Micaela','Morrissette','The Familiars'],
114: ['Steve Duffy','Duffy',"In the Lion's Den"],
115: ['Stephen Graham Jones','Graham Jones','Little Lambs'],
116: ['J. Robert Lennon','J. Robert','Lennon','The Portal'],
117: ['K. J. Bishop','K. J.','Bishop','Saving the Gleeful Horse'],
118: ['Afterweird'],
119: ['Lottery','The Lottery'],
120: ['The Falling','The Falling Girl'],
121: ['Before the Law'],
122: ['Laura Neato','Laura','Neato','Sredni Vashtar Graphic'],
123: ['Notes on Writing Weird Fiction', 'Notes on Writing Weird'],
124: ['Mark Fisher','Weird & Eerie','Fisher','The Weird and the Eerie']
}
